"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.variantFieldsToReadable = void 0;
exports.variantFieldsToReadable = {
    variant_id: "Variant ID",
    gene: "Gene",
    hgvsg: "HGVSg",
    hgvsp: "HGVSp",
    hgvsp_brief: "HGVSp Brief",
    exonic_func_known_gene: "Exonic Function Known Gene",
    transvar_input: "Transvar Input",
    clinical_phenotype: "Clinical Phenotype",
    source: "Source",
    neuropathology: "Neuropathology",
    info: "Info",
    dbsnp_id: "DbSNP ID",
    clnallele_id: "Clnallele ID",
    clnrevstat: "Clnrevstat",
    clnsig: "Clnsig",
    intervar_and_evidence: "Intervar And Evidence",
    pathogenecity_radr: "Pathogenecity RADR",
    chromosome: "Chromosome",
    position: "Position",
    ref: "Ref",
    alt: "Alt",
    gh38_gdna_coord: "GH38_gDNA_coord",
    mutation: "Mutation",
    region: "Region",
    pathogenecity_original: "Pathogenecity Original",
};
